-- AlterTable
ALTER TABLE "Track" ALTER COLUMN "title" SET DATA TYPE VARCHAR(45),
ALTER COLUMN "audio" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "art" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "username" SET DATA TYPE VARCHAR(45);
