name: End season
on:
  schedule:
    - cron: '1 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Monthly cron job
        run: |
          curl --request POST \
          --url 'https://dierad.xyz/api/season' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'